project:
  type: book
  output-dir: docs
  resources: 
    - "template_qmds/*"
    - "activities/*"

#number-depth: 2

book:
  title: "STAT 155: Intro to Statistical Modeling"
  subtitle: | 
    | Macalester College
    | Fall 2025 (UPDATE)
    | Prof ??? (UPDATE)
    |
    | <img src="images/curve_fitting_xkcd.png" alt="12 scatterplots of the same data with 12 different silly approaches to modeling the data" width=60% class="center"/>
    | image source: https://www.explainxkcd.com/wiki/index.php/2048:_Curve-Fitting
  # UPDATE the link below w the github repo where you'll host your manual
  #repo-url: https://github.com/???/???
  favicon: images/logo.png
  reader-mode: true
  # UPDATE the link below w the published manual site
  #site-url: https://???.github.io/???/
  sidebar:
    title: "STAT 155"
    style: "docked"
    collapse-level: 1
    search: true
  page-navigation: true
  chapters:
    - index.qmd
    - schedule.md
    - part: "Simple Linear Regression"
      chapters:
      - activities/L01-foundations-welcome.qmd
      # UPDATE as the semester progresses
      # List activities in relevent "part" or unit
    - part: "Multiple Linear Regression"
    - part: "Logistic Regression"
    - part: "Inference"
    - part: "Appendix"
      chapters:
      - activities/99-appendix.qmd

format:
  html:
    theme: united
    code-copy: true
    toc-title: "On this page"
    toc-depth: 1
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 150px
    execute:
      echo: true
      code-fold: true
      cache: false

editor: source
