project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!activity_templates/"
    - "!assignments/"
    - "!working/"
  post-render: "cp -r activities docs/activity_templates" # adds activity qmd as downloadable template
  resources:
    - "data/*.csv"
    # - "activity_templates/*.qmd"
    - "assignments/*.qmd"

website:
  title: "STAT 155"
  favicon: favicon-32x32.png
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: syllabus.qmd
        text: "Syllabus"
      - file: schedule.qmd
        text: "Schedule"
      - sidebar:activities
      - file: assignments.qmd
        text: "Practice Problems"
      - file: project.qmd
        text: "Project"
      - file: tech_setup.qmd
        text: "Tech Setup"

  sidebar:
    - id: activities
      title: "Activities"
      contents:
        - "activities/01_foundations_welcome.qmd"
  
  page-footer:
    left: |
      &copy; Jedidiah Carlson, 2025<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme:
      light: simplex
      dark: [simplex, simplex-dark.scss]
    # css: styles.css
    toc: true
    code-overflow: wrap

editor: source
