---
title: "Project"
sidebar: false
---

As noted in the syllabus, a detailed description of the group project can be found [here](https://docs.google.com/document/d/19bnUmovc6D_-3V8rwgJ1Wgfha1t-2qA4842GWdq6JwQ). Important dates and additional information are listed below.

### Important Dates

- Friday, February 28: Project Checkpoint 1 Due
- Friday, April 11: Project Checkpoint 2 Due
- Last day of class: Final Draft Due

### Grading

The final draft will be graded using the rubric found  [here](https://docs.google.com/spreadsheets/d/1yHYFqPwmK83aK0tPH8Qt0lTMeGFdtWZteNrQ0STXamw/edit?usp=sharing). Although the first two checkpoints will not directly contribute to your course grade, the feedback they allow me to provide will ensure the success of your final draft!

### Resources

Later in the semester, I will post at least one example of a successful final draft, as well as a google doc template for the final draft.

### Project Groups

Project groups will ultimately be determined by me, with the assistance of a Project Group Preferences survey. The survey will be sent out early in the semester (exact date TBD) and will allow you to either list people you would like to be in a group with or specify that you would like to be placed in a group randomly by me. I will do my best to ensure that groups are constructed as closely to survey responses as possible. Since one component of the project involves an in-class presentation, you may not work with students in different sections on the project.

If for any reason there is an individual (or individuals) with whom you do not feel safe participating in a project group with, there will be a space to note this on the survey. You will not be expected to provide any justification for your response to this question, but note that as I need to place you in groups, the survey will not be anonymous.

Group work and collaboration are important components of nearly all statistical analyses and projects. I recognize that individual contributions to a group project are not always consistent between group members. To this end, you will (as a group) be expected to explicitly specify the project tasks completed by each team member along with the final draft of your paper.

If there are any concerns with project groups throughout the semester, I am happy to meet with groups or individuals to discuss ways to move forward.