---
title: "Course Schedule"
sidebar: false
---

The course schedule below will be filled in throughout the semester. Any urgent announcements will be made over email.

+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Week      | Tuesday                                                 | Thursday                                                                                                                                                                                                                                     | Announcements                                                                                                               |
+===========+=========================================================+==============================================================================================================================================================================================================================================+=============================================================================================================================+
| 14        | 4/29: Project work day                                  | 5/1: Last day of class! (Project poster session)                                                                                                                                                                                             | -   See the [syllabus](https://carjed.github.io/155_spring_2025/syllabus.html#quizzes) for final quiz times the week of 5/5 |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 13        | 4/22: Project work day                                  | 4/24: P-value discussion                                                                                                                                                                                                                     | -   PP#8 due at 5pm on Wednesday 4/23 (Last homework                                                                        |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         | Before class:                                                                                                                                                                                                                                | -   Project presentation (*very* low-stakes) on 5/1 during class                                                            |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         | -   Do *your* assigned reading for today’s activity (Linked in Moodle Checkpoint)                                                                                                                                                            | -   Final Draft for project due 5/1 at Midnight!                                                                            |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         | ```{=html}                                                                                                                                                                                                                                   |                                                                                                                             |
|           |                                                         | <!-- -->                                                                                                                                                                                                                                     |                                                                                                                             |
|           |                                                         | ```                                                                                                                                                                                                                                          |                                                                                                                             |
|           |                                                         | -   To receive credit for today’s “checkpoint”, you must (1) have read your assigned reading in preparation for class and confirmed this on the Moodle Checkpoint Quiz, and (2) attend class and be an active participant in the discussion! |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 12        | 4/15: Hypothesis Testing Details                        | 4/17: Hypothesis Testing: Nested Models                                                                                                                                                                                                      | -   PP#7 due by 5pm on Wednesday, 4/16                                                                                      |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | Before class:                                                                                                                                                                                                                                | -   PP#8 due at 5pm on Wednesday 4/23 (Last homework!)                                                                      |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   complete today's Moodle checkpoint                  | -   complete today's Moodle checkpoint                                                                                                                                                                                                       |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 11        | 4/8: Confidence Intervals                               | 4/10: Hypothesis Testing Discovery                                                                                                                                                                                                           | -   PP#6 due by 5pm on Wednesday, 4/9                                                                                       |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | Before class:                                                                                                                                                                                                                                | -   Quiz corrections/reflections due by 11:59pm on Thursday, 4/10                                                           |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   complete today's Moodle checkpoint                  | -   no Moodle checkpoint due today!                                                                                                                                                                                                          | -   Project Checkpoint #2 is due Friday, 4/11                                                                               |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 10        | 4/1: The Normal model and sampling variation            | 4/3: Tools for inference                                                                                                                                                                                                                     | -   Last day to withdraw is Friday, 4/4                                                                                     |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | Before class:                                                                                                                                                                                                                                | -   No due dates this week                                                                                                  |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   complete today's Moodle checkpoint                  | -   complete today's Moodle checkpoint                                                                                                                                                                                                       |     -   PP#6 is due at 5pm on Wednesday, 4/9                                                                                |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         |                                                                                                                                                                                                                                              |     -   Project Checkpoint #2 is due Friday, 4/11                                                                           |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 9         | 3/25: Multiple Logistic Regression                      | 3/27: **Quiz 2** (1 hour in class)                                                                                                                                                                                                           | -   PP#5 due by 5pm on Wednesday, 3/26                                                                                      |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   complete today's Moodle checkpoint                  |                                                                                                                                                                                                                                              |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
|           | 3/18: NO CLASS (spring break!)                          | 3/20: NO CLASS (spring break!)                                                                                                                                                                                                               |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 8         | 3/11: Intro to Logistic Regression                      | 3/13: Review + Project Workday                                                                                                                                                                                                               | -   Midterm grades will be posted on Wednesday, 3/12                                                                        |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoints (two of them!)  |                                                                                                                                                                                                                                              |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 7         | 3/4: Model Building I                                   | 3/6: Model Building II                                                                                                                                                                                                                       | -   PP#4 due by 5pm Wednesday, 3/5                                                                                          |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | -   No Moodle checkpoint due today!                                                                                                                                                                                                          |                                                                                                                             |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoint                  |                                                                                                                                                                                                                                              |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 6         | 2/25: MLR interactions                                  | 2/27: NO CLASS TODAY                                                                                                                                                                                                                         | -   PP#3 due by 5pm Wednesday, 2/26                                                                                         |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | -   In lieu of class, please attend 2-3 MSCS Capstone Talks taking place today or Friday (view the schedule [here](https://drive.google.com/file/d/1qMmLsnG8PU88l92jb_lduGE5fudnnYJE/view?usp=sharing)).                                     | -   Project Checkpoint #1 due Friday, 2/28                                                                                  |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoint                  | -   Submit a short summary of the talks you attended [on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=183828)                                                                                                                |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 5         | 2/18: Intro to multiple linear regression               | 2/20: MLR confounding + project work day                                                                                                                                                                                                     | -   No homework due this week!                                                                                              |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | Before class:                                                                                                                                                                                                                                | -   Librarians will be in class for project help on Thursday                                                                |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoint                  | -   Complete today's Moodle checkpoint                                                                                                                                                                                                       |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 4         | 2/11: SLR categorical predictors                        | 2/13: **Quiz 1** (1 hour in class)                                                                                                                                                                                                           | -   PP#2 due by 5pm Wednesday, 2/12                                                                                         |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           |                                                                                                                                                                                                                                              | -   Group members for the final project are posted on Moodle                                                                |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoint                  |                                                                                                                                                                                                                                              |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 3         | 2/4: SLR model evaluation                               | 2/6: SLR variable transformations + library activity                                                                                                                                                                                         | -   PP#1 due by 5pm Wednesday, 2/5                                                                                          |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | Before class:                                                                                                                                                                                                                                | -   Please complete the project preferences survey by Friday, 2/7                                                           |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoint                  | -   Complete today's Moodle checkpoint                                                                                                                                                                                                       | -   See course Google Calendar for updated office hours                                                                     |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 2         | 1/28: Intro to R + univariate visualization & summaries | 1/30: Intro to simple linear regression                                                                                                                                                                                                      | -   Last day to add/drop is Friday, 1/31                                                                                    |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | Before class:                                           | Before class:                                                                                                                                                                                                                                | -   Preceptor office hours start this week–see the Google calendar for times                                                |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           | -   Complete today's Moodle checkpoint                  | -   Complete today's Moodle checkpoint                                                                                                                                                                                                       | -   PP#1 is posted on the [assignments](assignments.qmd) tab (due Wednesday, 2/5 at 5pm CT)                                 |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| 1         | Winter Break                                            | 1/23: First day of class!                                                                                                                                                                                                                    | Welcome back to campus!                                                                                                     |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         | Before class:                                                                                                                                                                                                                                |                                                                                                                             |
|           |                                                         |                                                                                                                                                                                                                                              |                                                                                                                             |
|           |                                                         | -   Review the [course syllabus](syllabus.qmd)                                                                                                                                                                                               |                                                                                                                             |
|           |                                                         | -   Familiarize yourself with Moodle and the course website                                                                                                                                                                                  |                                                                                                                             |
|           |                                                         | -   Complete the [Introductions survey](https://forms.gle/Wra1dy35ozJUAmNs8)                                                                                                                                                                 |                                                                                                                             |
|           |                                                         | -   [Download R and RStudio](tech_setup.qmd)                                                                                                                                                                                                 |                                                                                                                             |
+-----------+---------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+

<!-- ## Course Schedule & Announcements -->

<!-- ::: {.callout-tip icon=false collapse="false" title="Week 1: 1/23 - 1/31 (Data fundamentals, univariate visualization and summaries, and intro to simple linear regression)"} -->

<!-- #### Announcements -->

<!-- Welcome back to campus! -->

<!-- #### Thursday -->

<!-- Before class: -->

<!-- - Review the [course syllabus](syllabus.qmd)  -->

<!-- - Familiarize yourself with Moodle and the course website -->

<!-- - Complete the [Introductions survey](https://forms.gle/mXYCQfrz7Qryk1vW8) -->

<!-- - [Download R and RStudio](tech_setup.qmd) -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 2: 1/27 - 1/31 (Simple linear regression)"} -->

<!-- #### Announcements -->

<!-- - Practice Problems #1 will be due on Friday, 9/13 at 5pm! -->

<!-- - Friday, 9/13 is also the add/drop deadline -->

<!-- - Preceptor office hours start this week--see the course calendar for times -->

<!-- #### Tuesday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - Do either the readings or videos for the Day 3 Activity (see Moodle for links) -->

<!--   - due 30 minutes before class on 9/10 -->

<!-- #### Thursday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - Do either the readings or videos for the Day 4 Activity (see Moodle for links) -->

<!--   - due 30 minutes before class on 9/12 -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 3: 9/16 - 9/20 (Simple linear regression: model evaluation and variable transformations)"} -->

<!-- #### Announcements -->

<!-- - Practice Problems #2 will be due Friday, 9/20 at 5pm -->

<!-- - Reminder that preceptor office hours are held in the Sub-Hub (the glass room in the middle of the *first* floor of OLRI) -->

<!--   - see Moodle for the preceptor office hours calendar, or add [this calendar](https://calendar.google.com/calendar/u/5?cid=Y181NGJlMTEzOWZmYzE1YmI0ZDBmYTc2OGM2MGJiODFjYmZiM2M2MGFhM2Y1OTFjMTM3YjBlNzBiOTkwYmQ0NjlhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) in your Mac Google account -->

<!-- - Please remember to read your email 🥲 -->

<!-- #### Tuesday -->

<!-- Before class: -->

<!-- - Complete the [Project Preferences survey](https://forms.gle/1zrKb8c7pGwHjWxh7) -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - Do either the readings or videos for the Day 5 Activity (see Moodle for links) -->

<!--   - due 30 minutes before class on 9/17 -->

<!-- #### Thursday -->

<!-- Before class:  -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - Do either the readings or videos for the Day 6 Activity (see Moodle for links) -->

<!-- - Library data discovery day! -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 4: 9/23 - 9/27 (Simple linear regression: categorical predictors)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- Before class: -->

<!-- - No readings/videos/checkpoints for today! -->

<!-- #### Thursday -->

<!-- - Quiz 1 today (1 hour in class) -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 5: 9/30 - 10/4 (Multiple linear regression: principles + confounding)"} -->

<!-- #### Announcements -->

<!-- - Grades for Quiz #1 and PP #2 are posted on Moodle -->

<!-- - Practice Problems #3 will be due Friday, 10/4 at 5pm -->

<!-- #### Tuesday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - due 30 minutes before class on 10/1 -->

<!-- #### Thursday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - due 30 minutes before class on 10/3 -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 6: 10/7 - 10/11 (Multiple linear regression: interaction)"} -->

<!-- #### Announcements -->

<!-- - Practice Problems #4 will be due Friday, 10/11 at 5pm -->

<!-- - Try to submit Project Checkpoint #1 by Friday, 10/11 at 11pm -->

<!-- -  -->

<!-- #### Tuesday -->

<!-- #### Thursday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoints (note that there are two!) on Moodle -->

<!--   - due ~~30 minutes before class on 10/10~~ 30 minutes before usual class time on Friday, 10/11, since I forgot to open the checkpoints on Moodle at the usual time -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 7: 10/14 - 10/18 (Multiple linear regression: model building) (Fall Break)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- No Moodle checkpoint today -->

<!-- #### Thursday -->

<!-- No class! (Fall Break) -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 8: 10/21 - 10/25 (Logistic regression)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- #### Thursday -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 9: 10/28 - 11/1 (Tools for statistical inference)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- #### Thursday -->

<!-- Quiz #2 -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 10: 11/4 - 11/8 (Confidence intervals)"} -->

<!-- #### Announcements -->

<!-- PP#6 due on Friday, 11/8 at 5pm -->

<!-- #### Tuesday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - due 30 minutes before class on 11/5 -->

<!-- #### Thursday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - due 30 minutes before class on 11/7 -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="false" title="Week 11: 11/11 - 11/15 (Hypothesis testing)"} -->

<!-- #### Announcements -->

<!-- PP#7 due on Friday, 11/15 at 5pm -->

<!-- #### Tuesday -->

<!-- Before class: -->

<!-- - Complete today’s checkpoint on Moodle -->

<!--   - due 30 minutes before class on 11/12 -->

<!-- #### Thursday -->

<!-- Before class: -->

<!-- - No checkpoint due today -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 12: 11/18 - 11/22 (Hypothesis testing)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- #### Thursday -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 13: 11/25 - 11/29 (Hypothesis testing, p-values) (Thanksgiving Break)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- #### Thursday -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 14: 12/2 - 12/6 (Project work)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- #### Thursday -->

<!-- ::: -->

<!-- ::: {.callout-tip icon=false collapse="true" title="Week 15: 12/9 - 12/13 (Project work, paper, and presentations)"} -->

<!-- #### Announcements -->

<!-- #### Tuesday -->

<!-- (Last day of class) -->

<!-- ::: -->
